name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 2022
          user: ${{ secrets.SFTP_USER }}
          pass: ${{ secrets.SFTP_PASSWORD }}
          localDir: './'
          remoteDir: '/webroot'
          reverse: true
