name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Update live site
    runs-on: ubuntu-latest
    steps:
    - name: Fetch latest code
      uses: actions/checkout@v4
    
    - name: Upload files to server using SFTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PASSWORD }}
        server-dir: /webroot/
        port: 2022
