name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Upload new build to server
        uses: Atyn/simple-sftp-action@0.0.2
        with:
          url: sftp://${{ secrets.SFTP_USER }}:${{ secrets.SFTP_PASSWORD }}@${{ secrets.SFTP_HOST }}:2022/webroot
          local-directory: build-output
