name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  - upload:
      - name: Upload new build to server
        uses: Atyn/Simple-SFTP
        with:
          url: sftp://${{ secrets.SFTP_USER }}:${{ secrets.SFTP_PASSWORD }}@${{ secrets.SFTP_HOST }}:2022/webroot
          local-directory: build-output
