name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: (Optional) Set up the API request to trigger deployment via an API
    # If you're not using an API step, you can comment or remove this.
    # - name: Call API to trigger deployment
    #   env:
    #     API_KEY: ${{ secrets.API_KEY }}  # Store your API key in GitHub Secrets
    #   run: |
    #     curl -X POST \
    #       -H "Authorization: Bearer $API_KEY" \
    #       -d '{"action": "deploy"}' \
    #       https://your-api-endpoint.com/deploy

    # Step 3: Set up SFTP to upload files
    - name: Upload files to server using SFTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.SFTP_HOST }}  # Store the SFTP server address in GitHub Secrets
        username: ${{ secrets.SFTP_USER }}  # Store the SFTP username in GitHub Secrets
        password: ${{ secrets.SFTP_PASSWORD }}  # Store the SFTP password in GitHub Secrets
        local-dir: ./build  # Path to the local files you want to upload
        server-dir: /webroot  # Path on the server to upload files
        port: 2022  # Default SFTP port (adjust if necessary)
